name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust target
      run: |
        rustup target add thumbv8m.main-none-eabihf
    - name: Build-sf32lb52x
      run: cargo build --verbose --features "sf32lb52x rt defmt" --target thumbv8m.main-none-eabihf
